description: Build program


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''

  branch:
    description: platform
    required: false
    default: ''

  arch:
    description: platform
    required: false
    default: 'x64'



runs:
  using: composite

  steps:

  - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-branch
    with:
      branch: ${{ inputs.branch }}

      token: ${{ inputs.token }}
      auto: true


  - if: inputs.arch == 'x86' || inputs.arch == 'x64'
    uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
    with:
      arch: ${{ inputs.arch }}


  - shell: bash
    run: |
      merge () {
        echo "<<< ===  merging  $1  === >>>";
        if [[ -z "$2" ]]; then
          git merge origin/$1 || { git diff --diff-filter=U; exit 1; }
        else
          git merge origin/$1 || { git diff --diff-filter=U; git merge --abort; git merge -X $2 origin/$1; }
        fi
        echo "";
      }



  - if: inputs.arch == 'x86' || inputs.arch == 'x64'
    working-directory: ${{ github.workspace }}
    env:
      CC: ccache ${{ env.MINGW_CC }}
      CXX: ccache ${{ env.MINGW_CXX }}
    shell: bash
    run: |
      # make platform="win"


  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    env:
      MARSDEV: ${{ github.workspace }}/mars
      PATH_TO_SGDK: ${{ github.workspace }}/sgdk165
    shell: bash
    run: |
      sudo dpkg --add-architecture i386
      wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
      sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
      sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
      sudo apt install --install-recommends winehq-stable


      mkdir sgdk165
      cd sgdk165
      wget https://github.com/Stephane-D/SGDK/releases/download/v1.65/sgdk165.7z
      7z x sgdk165.7z
      chmod 777 -R .
      cd bin

      wget https://github.com/Franticware/SGDK_wine/raw/e3716d4000f24e914f500070be210c4ba19b2258/generate_wine.sh
      chmod 777 -R .
      sh generate_wine.sh

      cd ${{ github.workspace }}
      make GDK=$PATH_TO_SGDK -f $PATH_TO_SGDK/makefile_wine.gen


  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    env:
      MARSDEV: ${{ github.workspace }}/mars
      PATH_TO_SGDK: ${{ github.workspace }}/sgdk165
    shell: bash
    run: |
      # wget https://github.com/andwn/marsdev/releases/download/2017.09.12/marsdev-nosh-nogdb.tar.bz2
      # tar -xvf marsdev-nosh-nogdb.tar.bz2

      # wget https://github.com/andwn/marsdev/releases/download/2018.01/mars-2018jan-linux.zip
      # 7z x mars-2018jan-linux.zip

      # wget https://github.com/andwn/marsdev/releases/download/2020.01/mars-linux64-2020jun5.tar.xz
      # tar -xvf mars-linux64-2020jun5.tar.xz

      # wget https://github.com/andwn/marsdev/releases/download/2021.04/mars-linux-x86_64-2021.04.tar.xz
      # tar -xvf mars-linux-x86_64-2021.04.tar.xz

      # wget https://github.com/andwn/marsdev/releases/download/2022.09/mars-2022.09-linux-x64.tar.xz
      # tar -xvf mars-2022.09-linux-x64.tar.xz

      # chmod 777 -R .
      # ./mars/m68k-elf/bin/m68k-elf-gcc --version
      # make


  - uses: actions/upload-artifact@main
    with:
      name: ym2020_${{ inputs.arch }}
      path: |
        ${{ github.workspace }}/**.bin
        ${{ github.workspace }}/out/rom.out
